import Foundation
import NablaCore

public struct DocumentFile: Media, Equatable, Hashable {
    public let fileName: String
    /// URL of the thumbnail. Generated by the backend.
    public let thumbnail: ImageSource?
    public let content: MediaSource
    public let documentMimeType: MimeType.Document

    public var mimeType: MimeType {
        .document(documentMimeType)
    }

    public init(fileName: String, content: MediaSource, thumbnail: ImageSource?, mimeType: MimeType.Document) {
        self.fileName = fileName
        self.content = content
        self.thumbnail = thumbnail
        documentMimeType = mimeType
    }
}
