import Foundation
import NablaCore

public struct DocumentFile: Media, Equatable, Hashable {
    public let fileName: String
    /// URL of the thumbnail. Generated by the backend.
    public let thumbnailUrl: URL?
    public let fileUrl: URL
    public let documentMimeType: MimeType.Document

    public var mimeType: MimeType {
        .document(documentMimeType)
    }

    public init(fileName: String, fileUrl: URL, thumbnailUrl: URL?, mimeType: MimeType.Document) {
        self.fileName = fileName
        self.fileUrl = fileUrl
        self.thumbnailUrl = thumbnailUrl
        documentMimeType = mimeType
    }
}
