import Foundation
import NablaCore

public struct DocumentFile: Media, Equatable, Hashable {
    public let fileName: String
    /// URL of the thumbnail. Generated by the backend.
    public let thumbnailUrl: URL?
    public let content: MediaContent
    public let documentMimeType: MimeType.Document

    public var mimeType: MimeType {
        .document(documentMimeType)
    }

    public init(fileName: String, content: MediaContent, thumbnailUrl: URL?, mimeType: MimeType.Document) {
        self.fileName = fileName
        self.content = content
        self.thumbnailUrl = thumbnailUrl
        documentMimeType = mimeType
    }
}
