import Foundation

/// Medias are a representation of a file.
/// Those can be created with a local fileUrl, or a remote one.
public struct Media: Equatable, Hashable {
    public struct Size: Hashable {
        public let width: Int
        public let height: Int

        public init(width: Int, height: Int) {
            self.width = width
            self.height = height
        }
    }
    
    public let type: MediaType
    public let fileName: String
    /// URL of the thumbnail. Generated by the backend.
    public let thumbnailUrl: URL?
    public let fileUrl: URL
    public let mimeType: MimeType
    public let size: Size?
    
    public init(
        type: MediaType,
        fileName: String,
        fileUrl: URL,
        thumbnailUrl: URL?,
        mimeType: MimeType,
        size: Size?
    ) {
        self.type = type
        self.fileName = fileName
        self.fileUrl = fileUrl
        self.thumbnailUrl = thumbnailUrl
        self.mimeType = mimeType
        self.size = size
    }
}
