import Foundation

/// Medias are a representation of a file.
/// Those can be created with a local fileUrl, or a remote one.
public struct Media: Equatable, Hashable {
    public let type: MediaType
    public let fileName: String
    /// URL of the thumbnail. Generated by the backend.
    public let thumbnailUrl: URL?
    public let fileUrl: URL
    public let mimeType: MimeType
    
    public init(type: MediaType, fileName: String, fileUrl: URL, thumbnailUrl: URL?, mimeType: MimeType) {
        self.type = type
        self.fileName = fileName
        self.fileUrl = fileUrl
        self.thumbnailUrl = thumbnailUrl
        self.mimeType = mimeType
    }
}
